enemy_color: "red"
# enemy_color: "blue"

#####-----神经网络参数-----#####
yolo_name: yolov5
classify_model: assets/tiny_resnet.onnx
yolo11_model_path: assets/yolo11.xml
yolov8_model_path: assets/yolov8.xml
yolov5_model_path: assets/yolov5.xml
device: GPU
min_confidence: 0.7 #0.8 #原检测阈值
use_traditional: true

#####-----ROI-----#####
roi: 
  x: 420
  y: 50
  width: 600
  height: 600

use_roi: false

#####-----传统方法参数-----#####
threshold: 150
max_angle_error: 45 # degree
min_lightbar_ratio: 1.5
max_lightbar_ratio: 20
min_lightbar_length: 8
min_armor_ratio: 1
max_armor_ratio: 5
max_side_ratio: 1.5
max_rectangular_error: 25 # degree
# min_confidence: 0.8

#####-----tracker参数-----#####
min_detect_count: 5               #追踪检测次数阈值
max_temp_lost_count: 15           #装甲板最大丢失帧数
outpost_max_temp_lost_count: 75   #前哨站最大丢失帧数

#####-----aimer参数-----#####
yaw_offset: 0 # degree -2.5
pitch_offset: 0 # degree 2
comming_angle: 60 # degree
leaving_angle: 20 # degree
decision_speed: 8 # rad/s
high_speed_delay_time: 0.015 # s
low_speed_delay_time: 0.015 # s

#####-----shooter参数-----#####
first_tolerance: 3 # 近距离射击容差，degree
second_tolerance: 2 # 远距离射击容差，degree
judge_distance: 2 #距离判断阈值
auto_fire: true # 是否由自瞄控制射击


camera_name: "hikrobot"
exposure_ms: 2
gamma: 12
user_id: I


# 重投影误差: 0.1849px
R_gimbal2imubody: [1, 0, 0, 0, 0, 1, 0, 1, 0]

# 重投影误差: 0.1849px
camera_matrix: [2383.3681559952665, 0, 774.8338738671373, 0, 2387.5057839956175, 555.78346643326233, 0, 0, 1]
distort_coeffs: [-0.035785554965348812, 0.16596820153709058, -0.00077060838768365644, 0.0016891085752592772, 0]


# 相机同理想情况的偏角: yaw43.94 pitch-59.53 roll135.51 degree
R_camera2gimbal: [0.059877377066425597, 0.92901190619470908, 0.36517335316821525, 0.93278805216464877, 0.078181060847750006, -0.35184395896988324, -0.35541686714972542, 0.36169683420399656, -0.86188992955729615]
t_camera2gimbal: [-0.06485337091829281, 0.025540551220232601, -0.032906950591694246]
